application.version: ${version}

logging:
  logback:
    rollingpolicy:
      max-history: 7
      total-size-cap: 1GB
      clean-history-on-start: true
      max-file-size: 10MB
  file:
    name: \${user.home}/.komga/komga.log
  level:
    org.apache.activemq.audit: WARN

komga:
  libraries-scan-cron: "0 0 */8 * * ?"
  libraries-scan-directory-exclusions:
    - "#recycle"
    - "@eaDir"
  database:
    file: \${user.home}/.komga/database.sqlite
  lucene:
    data-directory: \${user.home}/.komga/lucene
  session-timeout: 7d

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    mixed: true
    placeholders:
      library-file-hashing: \${komga.file-hashing:true}
  thymeleaf:
    prefix: classpath:/public/
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 1h
  artemis:
    embedded:
      persistent: true
      data-directory: \${user.home}/.komga/artemis
  web:
    resources:
      add-mappings: false

server:
  servlet.session.timeout: 7d
  forward-headers-strategy: framework
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health:
      roles: ADMIN
      show-details: when_authorized
    shutdown:
      enabled: true
  metrics:
    export:
      influx:
        enabled: false
springdoc:
  group-configs:
    - group: REST API
      paths-to-match: /api/**
    - group: OPDS
      paths-to-match: /opds/**
  swagger-ui:
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
